name: CD 

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código
        uses: actions/checkout@v3

      - name: Loguearse en DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir la imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/eventhub:latest .

      - name: Subir imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/eventhub:latest

  deploy:
    name: Deploy a Render
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Llamar al deploy de Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }} \
          -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
          -H 'Accept: application/json'
