# Generated by Django 5.2 on 2025-04-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_refundrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
