name: CD

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - main  # para deploy continuo al mergear PRs a main

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || 'v0.2.0' }}

    steps:
      - name: Clonar el código
        uses: actions/checkout@v3

      - name: Loguearse en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/eventhub:${{ env.IMAGE_TAG }} \
            .

      - name: Subir imagen
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/eventhub:${{ env.IMAGE_TAG }}